services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwCaptcha\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Blueways\BwCaptcha\Controller\CaptchaController:
    public: true