web_environment:
  - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
  - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_PRIMARY_URL}
  - SIMPLETEST_BASE_URL=http://web
  - SIMPLETEST_DB=mysql://db:db@db/db
  - MINK_DRIVER_ARGS_WEBDRIVER=["chrome", {"browserName":"chrome","goog:chromeOptions":{"w3c":true,"args":["--disable-dev-shm-usage","--disable-gpu","--headless","--dns-prefetch-disable"]}}, "http://selenium-chrome:4444/wd/hub"]
